//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by sendmap20.rc
//
#define ID_LICENCE                      8
#define ID_EXPIRATION                   9
#define ID_INFO                         10
#define ID_MAIN                         11
#define IDI_ICON1                       101
#define IDD_PROGRESS                    102
#define ID_PROGRESS                     102
#define ID_PROGRESS_SYNC                103
#define ID_EXE_CREATE                   104
#define ID_KEY                          105
#define IDC_EDIT1                       1001
#define IDS_CONNECT_ENG                 1001
#define IDC_EDIT_KEY                    1001
#define IDC_EDIT2                       1002
#define IDS_REMOVE_MAPS_ENG             1002
#define IDC_EDIT_KEY2                   1002
#define IDS_ADD_MAPS_ENG                1003
#define IDS_EXIT_ENG                    1004
#define IDS_UPLOAD_ENG                  1005
#define IDC_EDIT_KEY5                   1005
#define IDS_ERASE_ENG                   1006
#define IDC_EDIT_KEY6                   1006
#define IDS_MAPS_STATIC_ENG             1007
#define IDC_EDIT_KEY7                   1007
#define IDC_RICHEDIT22                  1008
#define IDS_SIZE_STATIC_ENG             1008
#define IDC_LIST1                       1009
#define IDC_IMG_LIST                    1009
#define IDS_DEVICE_STATIC_ENG           1009
#define IDS_SPEED_STATIC_ENG            1010
#define IDS_FOUND_STATIC_ENG            1011
#define IDC_PORTS                       1012
#define IDS_NO_GPS_ENG                  1012
#define IDC_ADD_MAPS                    1013
#define IDS_NO_GPS_TITLE_ENG            1013
#define IDC_REMOVE_MAPS                 1014
#define IDS_SYNC_GPS_ENG                1014
#define IDC_APPEND                      1015
#define IDS_SYNC_START_ENG              1015
#define IDC_UPLOAD                      1016
#define IDS_SYNC_TITLE_ENG              1016
#define IDC_EXIT                        1017
#define IDS_SENDING_ENG                 1017
#define ID_CONNECT                      1018
#define IDS_RELOCATING_ENG              1018
#define IDC_SPEEDS                      1019
#define IDS_IMG_FILE_ENG                1019
#define IDC_ERASE                       1020
#define IDS_EXE_FILE_ENG                1020
#define IDC_GPS_TEXT                    1021
#define IDS_WRONG_KEY_TITLE_ENG         1021
#define IDC_ADD_UNLOCK                  1022
#define IDS_WRONG_KEY_ENG               1022
#define IDC_PROGRESS                    1023
#define IDC_REMOVE_MAPS2                1023
#define IDC_SYNC_GPS                    1023
#define IDS_ADD_UNLOCK_ENG              1023
#define IDC_SIZE_TOTAL                  1024
#define IDC_PROGRESS2                   1024
#define IDC_MAPS_STATIC                 1025
#define IDC_SIZE_STATIC                 1026
#define IDC_DEVICE_STATIC               1027
#define IDC_SPEED_STATIC                1028
#define IDC_FOUND_STATIC                1029
#define IDC_STATIC_SYNC_PROGRESS        1030
#define IDC_IMG_FILE                    1030
#define IDC_PROGRESS_DOWN               1031
#define IDC_EXE_FILE                    1031
#define IDC_SIZE_STATIC2                1032
#define IDC_EDIT_MAPSET                 1033
#define IDC_CHECK1                      1034
#define IDC_SIZE_STATIC3                1034
#define IDC_CHECK2                      1035
#define IDC_EDIT_MAPSET2                1035
#define IDC_EDIT_REGION                 1035
#define IDC_EXE_CREATE                  1036
#define IDC_SYNC_GPS2                   1036
#define IDC_STORE_FILES                 1036
#define IDC_CHECK3                      1037
#define IDC_OLD_HEADER                  1037
#define IDC_NT_FORMAT                   1037
#define IDC_BUTTON_GET_ID               1038
#define IDC_STATIC_KEY                  1039
#define IDC_EDIT_ENTER_KEY              1040
#define IDC_ADD                         1042
#define IDS_CONNECT                     2001
#define IDS_REMOVE_MAPS                 2002
#define IDS_ADD_MAPS                    2003
#define IDS_EXIT                        2004
#define IDS_UPLOAD                      2005
#define IDS_ERASE                       2006
#define IDS_MAPS_STATIC                 2007
#define IDS_SIZE_STATIC                 2008
#define IDS_DEVICE_STATIC               2009
#define IDS_SPEED_STATIC                2010
#define IDS_FOUND_STATIC                2011
#define IDS_NO_GPS                      2012
#define IDS_NO_GPS_TITLE                2013
#define IDS_SYNC_GPS                    2014
#define IDS_SYNC_START                  2015
#define IDS_SYNC_TITLE                  2016
#define IDS_SENDING                     2017
#define IDS_RELOCATING                  2018
#define IDS_IMG_FILE                    2019
#define IDS_EXE_FILE                    2020
#define IDS_WRONG_KEY_TITLE             2021
#define IDS_WRONG_KEY                   2022
#define IDS_ADD_UNLOCK                  2023
#define IDS_ADD_UNLOCK3                 2024
#define IDS_CONNECT_FRA                 3001
#define IDS_REMOVE_MAPS_FRA             3002
#define IDS_ADD_MAPS_FRA                3003
#define IDS_EXIT_FRA                    3004
#define IDS_UPLOAD_FRA                  3005
#define IDS_ERASE_FRA                   3006
#define IDS_MAPS_STATIC_FRA             3007
#define IDS_SIZE_STATIC_FRA             3008
#define IDS_DEVICE_STATIC_FRA           3009
#define IDS_SPEED_STATIC_FRA            3010
#define IDS_FOUND_STATIC_FRA            3011
#define IDS_NO_GPS_FRA                  3012
#define IDS_NO_GPS_TITLE_FRA            3013
#define IDS_SYNC_GPS_FRA                3014
#define IDS_SYNC_START_FRA              3015
#define IDS_SYNC_TITLE_FRA              3016
#define IDS_SENDING_FRA                 3017
#define IDS_RELOCATING_FRA              3018
#define IDS_IMG_FILE_FRA                3019
#define IDS_EXE_FILE_FRA                3020
#define IDS_WRONG_KEY_TITLE_FRA         3021
#define IDS_WRONG_KEY_FRA               3022
#define IDS_ADD_UNLOCK_FRA              3023

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1043
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
